spring:
  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017/customers?authSource=admin&directConnection=true
#      host: localhost
#      port: 27017
#      database: customers
#      username: user
#      password: pass
#      authentication-database: admin

server:
  port: 8090